### ISSUE TITLE
ES 1.4.4 plugin returns file content instead of lang value

### ISSUE THREAD

**Issue by vspiridonov** [jprante/elasticsearch-langdetect#25]
Just installed the plugin and execute some search queries.

PUT
{
	"content": "IkdvZCBTYXZlIHRoZSBRdWVlbiIgKGFsdGVybmF0aXZlbHkgIkdvZCBTYXZlIHRoZSBLaW5nIg=="
}

SEARCH

{
	"fields" : "content.language.lang",
    "query" : {
        "match_all" : {}
    }
}

RESULT 

.................

"fields": {
                    "content.language.lang": [
                        "IkdvZCBTYXZlIHRoZSBRdWVlbiIgKGFsdGVybmF0aXZlbHkgIkdvZCBTYXZlIHRoZSBLaW5nIg=="
                    ]
                }

As we can see the content.language.lang is not as expected.

Any ideas?

**Comment by jprante** [comment]
Thanks!

I changed the default binary detection for multi-fields, there was a mistake. It should work now with new plugin version 1.4.4.0.

**Comment by vspiridonov** [comment]
You are welcome.
Try it with newest version - the result is the same.

**Comment by jprante** [comment]
Next try, version 1.4.4.1

I added a test to ensure this works. The cause of the trouble was the field being not stored.

**Comment by vspiridonov** [comment]
Confirmed!

**Comment by Manko10** [comment]
I still have the same problem. Using Elasticsearch 1.4.4 with langdetect 1.4.4.2. The REST endpoint works, but the mapping does not. Indexing data to the field only stores the raw content.

**Comment by vspiridonov** [comment]
Would you share your mapping?

**Comment by Manko10** [comment]
Hi, sorry for the late reply.
My mapping is pretty similar to the example mapping from the README. In fact, I even tried the exact examples as they were described there. Still, there is no language flag. When I search for it, I get an empty result and when I just dump the JSON docs, there is no language flag either, just the plain content.
